name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: macos-latest
            compiler: clang

    steps:
    - uses: actions/checkout@v2

    - name: Setup CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latestrc

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        echo "CMake finished building"
        mkdir user-build
        mv ../std.lf user-build/
        mv logic_flow user-build/

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logic_flow-${{ matrix.os }}
        path: build/user-build

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            compiler: msvc
    steps:
    - uses: actions/checkout@v2

    - name: Setup CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latestrc

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        echo "CMake finished building"
        mkdir user-build
        mv ../std.lf user-build/
        ls
        mv Debug/logic_flow.exe user-build/

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logic_flow-${{ matrix.os }}
        path: build/user-build

  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download Artifacts
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: logic_flow-ubuntu-latest
  #       path: ./artifacts

  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: Release ${{ github.ref }}
  #       draft: false
  #       prerelease: false

  #   - name: Upload Release Asset
  #     uses: actions/upload-release-asset@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       upload_url: ${{ steps.create_release.outputs.upload_url }}
  #       asset_path: ./artifacts
  #       asset_name: logic_flow-ubuntu-latest.zip
  #       asset_content_type: application/zip
